# Generated by Django 5.1.6 on 2025-03-13 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_fit',
            field=models.CharField(blank=True, choices=[('petite', 'Petite'), ('regular', 'Regular'), ('plus_size', 'Plus Size')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty'), ('Party Wears', 'Party Wears'), ('jackets', 'Jackets')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_new',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New Season')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty'), ('Party Wears', 'Party Wears')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('eco_friendly', 'Eco-Friendly')], default='clothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Untitled Product', max_length=255),
        ),
    ]
