# Generated by Django 5.1.6 on 2025-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_body_fit_product_clothing_type_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('bamboo', 'Bamboo'), ('recycled_plastic', 'Recycled Plastic'), ('organic_cotton', 'Organic Cotton')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Eco-Friendly'), ('certified', 'Certified Sustainable'), ('premium', 'High-Grade Sustainable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_fit',
            field=models.CharField(blank=True, choices=[('petite', 'Petite'), ('regular', 'Regular'), ('plus_size', 'Plus Size')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_new',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New Season')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty'), ('Party Wears', 'Party Wears')], max_length=50, null=True),
        ),
    ]
