# Generated by Django 5.1.6 on 2025-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_material_product_sustainability_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='earring_type',
            field=models.CharField(blank=True, choices=[('stud', 'Stud'), ('hoop', 'Hoop'), ('drop', 'Drop')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='necklace_type',
            field=models.CharField(blank=True, choices=[('choker', 'Choker'), ('pendant', 'Pendant'), ('chain', 'Chain')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty'), ('party_wear', 'Party Wears'), ('jackets', 'Jackets')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sporty', 'Sporty'), ('party_wear', 'Party Wears')], max_length=50, null=True),
        ),
    ]
