# Generated by Django 5.1.6 on 2025-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_earring_type_product_necklace_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('eco_friendly', 'Eco-Friendly')], db_index=True, default='clothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], db_index=True, max_length=5, null=True),
        ),
    ]
