# Generated by Django 5.1.6 on 2025-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('vegan_leather', 'Vegan Leather'), ('organic_cotton', 'Organic Cotton'), ('hemp', 'Hemp'), ('bamboo_cotton', 'Bamboo Cotton')], max_length=50, null=True),
        ),
    ]
