# Generated by Django 5.1.6 on 2025-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('necklaces', 'Necklaces'), ('earrings', 'Earrings')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='necklace_type',
            field=models.CharField(blank=True, choices=[('choker', 'Chokers'), ('pendant', 'Pendants'), ('chain', 'Chains')], max_length=50, null=True),
        ),
    ]
