# Generated by Django 5.1.6 on 2025-05-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_status',
        ),
    ]
