# Generated by Django 5.1.6 on 2025-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalti_payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaltitransaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='khaltitransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='khaltitransaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='khaltitransaction',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
